### ISSUE TITLE
FR: Add support for client certificates

### ISSUE THREAD

**Issue by ogarcia** [kubewall/kubewall#17]
Many Kubernetes servers (such as Azure AKS) use client certificates to connect (`client-certificate-data` and `client-key-data` fields). As far as I see right now this should not be supported as kubewall does not import these connections from the kubeconfig.

It would be interesting to add support for these connections so that they can be used with this type of servers.

**Comment by abhimanyu003** [comment]
Hello @ogarcia 
Thanks for reaching out. 
This feature is supported I have tested it on Google Cloud, but I don't have access to Azure.

Google Cloud supports token-based auth as well. Is it something that be used with Azure?

Also on my Local, I have a kind and orbstack cluster that contains.
```
kind: Config
preferences: {}
users:
  - name: kwok-kwok
    user:
      client-certificate: /pathTo/pki/admin.crt
      client-key: /pathTo/pki/admin.key
  - name: orbstack
    user:
      client-certificate-data: <REDACTED>
      client-key-data: <REDACTED>
 ```
Can you try once using **Add Config > Certificate**

<img width="542" alt="image" src="https://github.com/user-attachments/assets/97a42644-bcd2-4c63-9218-b325bb5ad2bd">

I will try to test on Azure and other with other providers once more.

**Comment by ogarcia** [comment]
In Azure, the configuration is similar to the following:
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <REDACTED>
    server: https://servername.westeurope.azmk8s.io:443
  name: servername
contexts:
- context:
    cluster: servername
    user: clusterUser_servername
  name: servername
kind: Config
preferences: {}
users:
- name: clusterUser_servername
  user:
    client-certificate-data: <REDACTED>
    client-key-data: <REDACTED>
    token: <REDACTED>
```

If I try to enter the data by hand in **Add Config > Certificate** I get this error:
```
Failure
serverIP or name or clientCertData or clientKeyData is empty
```

In my case both the `certificate-authority-data` value and the `client-certificate-data` and `client-key-data` values are a single single line string (in base64). When I enter it by hand I get exactly the same error using that string as I did previously decoding the base64 content to the certificate and key.

**Comment by ogarcia** [comment]
One thing you can do is to have a `main` docker tag containing the latest version of the `main` git branch (created with a GitHub action). This way when you upload a patch we can test it directly with that container. :wink: 

I have compiled the git version and now it accepts the data manually (it still doesn't load them from `kubeconfig`), but when I can only pass the certificate and the key it gives this error:

`W0922 08:50:02.707692       3 reflector.go:561] k8s.io/client-go@v0.31.1/tools/cache/reflector.go:243: failed to list *v1.Namespace: Get "https://servername.westeurope.azmk8s.io:443/api/v1/namespaces?limit=500&resourceVersion=0": tls: failed to verify certificate: x509: certificate signed by unknown authority`

`E0922 08:50:02.707859       3 reflector.go:158] "Unhandled Error" err="k8s.io/client-go@v0.31.1/tools/cache/reflector.go:243: Failed to watch *v1.Namespace: failed to list *v1.Namespace: Get \"https://servername.westeurope.azmk8s.io:443/api/v1/namespaces?limit=500&resourceVersion=0\": tls: failed to verify certificate: x509: certificate signed by unknown authority" logger="UnhandledError"
`

I understand that to avoid this it would have to have the possibility to configure also the `certificate-authority-data` so it can check the certificate with that authority.

**Comment by abhimanyu003** [comment]
I will expand on logs as well to know more.

If you get a chance, please try adding `insecure-skip-tls-verify: true` flag to a new config.

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <REDACTED>
    server: https://servername.westeurope.azmk8s.io:443
    insecure-skip-tls-verify: true <---------------------  ADDED THIS LINE
  name: servername
contexts:
- context:
    cluster: servername
    user: clusterUser_servername
  name: servername
kind: Config
preferences: {}
users:
- name: clusterUser_servername
  user:
    client-certificate-data: <REDACTED>
    client-key-data: <REDACTED>
    token: <REDACTED>
````

**Comment by abhimanyu003** [comment]
I will try to see what I can do with `main` branch, also will expand on logs so that we know more.

If you get a chance please try one thing.

```
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true <-------------- ADD THIS LINE
    # certificate-authority-data: <REDACTED> <-------------- COMMENT OR REMOVE THIS LINE
    server: https://servername.westeurope.azmk8s.io:443
  name: servername
contexts:
- context:
    cluster: servername
    user: clusterUser_servername
  name: servername
kind: Config
preferences: {}
users:
- name: clusterUser_servername
  user:
    client-certificate-data: <REDACTED>
    client-key-data: <REDACTED>
    token: <REDACTED>
  ```
