### ISSUE TITLE
Error "specifying a root certificates file with the insecure flag is not allowed"

### ISSUE THREAD

**Issue by SlavikCA** [kubewall/kubewall#25]
When my cluster config defined with "certificate-authority-data" like this:
```
- cluster:
    server: "https://192.168.0.222/k8s/clusters/local"
    certificate-authority-data: "<redacted>"
  name: harvester
```
I'm getting error:
> WARN failed to load clientConfig for cluster err="failed to create kubernetes clientset: specifying a root certificates file with the insecure flag is not allowed"

The only way to make it work is with insecure-skip-tls-verify:
```
- cluster:
    server: "https://192.168.0.222/k8s/clusters/local"
    insecure-skip-tls-verify: true
  name: harvester
```

Can you please support the config with `certificate-authority-data`?

I'm getting this Kube config from my Harvester cluster.

Kubewall
- version: 0.0.5
- commit: 2a51071

**Comment by abhimanyu003** [comment]
Hello @SlavikCA thanks for reaching out !!

> specifying a root certificates file with the insecure flag is not allowed 

this error is from k8s client, can you please double-check if you have any config file in the `~/.kube` directory that contains both  `certificate-authority-data:` and `insecure-skip-tls-verify` and exists together for single cluster.

```
apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: "<redacted>" <---- this
      insecure-skip-tls-verify: true <----- this
      server: https://127.0.0.1:26443
    name: mycluster
```
