### ISSUE TITLE
Feature Request: respect default namespace of context from .kube/config

### ISSUE THREAD

**Issue by sgohl** [kubewall/kubewall#87]
Consider this `.kube/config`

```
contexts:
- context:
    cluster: default
    namespace: acmespace
    user: default
  name: default
current-context: default
kind: Config
```

It would be nice to have this namespace selected as pre-selected namespace in the web app

Some users might not know what a namespace actually is and thus they're not aware that they actually need to select the right thing in the dropdown menu.

So far I very much like this app, it's far better suited for end-users like developers than the full-blown alternatives like Rancher 👍 

I'm eagerly waiting for the `kubectl exec` functionality to be included!
